import { Trispace } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { CartProvider } from "@/Context/CartContext";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const trispace = Trispace({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Timbu HNG Bookstore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={trispace.className}>
        <CartProvider>
          <ToastContainer />
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
