import { Trispace as TrispaceFont } from "next/font/google";
import "./globals.css";

const trispace = TrispaceFont({ subsets: ["latin"], weight: ['400', '500', '600', '700'] });

export const metadata = {
  title: "Timbo-Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={trispace.className}>{children}</body>
    </html>
  );
}
